/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Native */

#ifndef _Included_org_example_Native
#define _Included_org_example_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Native
 * Method:    redefineClass
 * Signature: ([Ljava/lang/Class;[[B)V
 */
JNIEXPORT void JNICALL Java_org_example_Native_redefineClass
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

/*
 * Class:     org_example_Native
 * Method:    retransformClass
 * Signature: ([Ljava/lang/Class;[[B)V
 */
JNIEXPORT void JNICALL Java_org_example_Native_retransformClass
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

/*
 * Class:     org_example_Native
 * Method:    accessClass
 * Signature: (Ljava/lang/String;)Ljava/util/Optional;
 */
JNIEXPORT jobject JNICALL Java_org_example_Native_accessClass
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
